@Catalog.Api_HostAddress = https://localhost:5001

POST {{Catalog.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "product": {
    "name": "name 1",
    "category": "category 1",
    "description": "description 1",
    "imageFile": "image file 1",
    "price": 100
  }
}

###
PUT {{Catalog.Api_HostAddress}}/api/products/D4CC6605-B105-4C7E-7431-08DCABC4A6F6
Content-Type: application/json

{
  "product": {
    "id": "",
    "name": "name 1",
    "category": "category 1",
    "description": "description 1",
    "imageFile": "image file 1",
    "price": 100
  }
}

###
DELETE {{Catalog.Api_HostAddress}}/api/products/A61C5EB4-5B80-46EF-C78F-08DCAC47D91D

###
GET {{Catalog.Api_HostAddress}}/api/products?pageNum=0&pageSize=20
Accept: application/json

###
GET {{Catalog.Api_HostAddress}}/api/products/5f465145-c9da-4012-721e-08dcabecd23f
Accept: application/json

