@Catalog.Api_HostAddress = https://localhost:5001

POST {{Catalog.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "product": {
    "name": "name",
    "category": ["category 1", "category 2"],
    "description": "description",
    "imageFile": "image file",
    "price": 50
  }
}

###
PUT {{Catalog.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "product": {
    "id": "45859469-6713-4bd4-1c95-08dcacfa056e",
    "name": "name",
    "category": ["category 1", "category 2"],
    "description": "description",
    "imageFile": "image file",
    "price": 80
  }
}

###
DELETE {{Catalog.Api_HostAddress}}/api/products/45859469-6713-4bd4-1c95-08dcacfa056e

###
GET {{Catalog.Api_HostAddress}}/api/products?pageNum=0&pageSize=20
Accept: application/json

###
GET {{Catalog.Api_HostAddress}}/api/products/45859469-6713-4bd4-1c95-08dcacfa056e
Accept: application/json

