@Catalog.Api_HostAddress = https://localhost:5001

POST {{Catalog.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "product": {
    "name": "name",
    "category": "category",
    "description": "description",
    "imageFile": "image file",
    "price": 50
  }
}

###
PUT {{Catalog.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "product": {
    "id": "5d87f504-583f-402e-7cd1-08dcac4ff7e6",
    "name": "name",
    "category": "category",
    "description": "description",
    "imageFile": "image file",
    "price": 80
  }
}

###
DELETE {{Catalog.Api_HostAddress}}/api/products/5005EF70-79CC-4E27-721F-08DCABECD23F

###
GET {{Catalog.Api_HostAddress}}/api/products?pageNum=0&pageSize=20
Accept: application/json

###
GET {{Catalog.Api_HostAddress}}/api/products/5d87f504-583f-402e-7cd1-08dcac4ff7e6
Accept: application/json

